services:
  airflow-init:
    container_name: airflow-init-2
    image: apache/airflow:2.8.1 # image là phiên bản mới nhất của Airflow
    environment: # # biến môi trường để cấu hình Airflow
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@postgres:5432/airflow"
      AIRFLOW__CORE__FERNET_KEY: "${FERNET_KEY}"
    command: > # # khởi tạo cơ sở dữ liệu Airflow
      bash -c "
      airflow db init &&
      airflow users create --username admin --firstname Data --lastname Engineer --role Admin --email admin@airflow.com --password admin
      "
    networks:
      - default

  airflow-webserver:
    image: apache/airflow:2.8.1
    command: webserver 
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@postgres:5432/airflow"
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: "${FERNET_KEY}"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__WEBSERVER__WEB_SERVER_PORT: 8080
      AIRFLOW__CORE__LOGGING_LEVEL: DEBUG
      AIRFLOW__SCHEDULER__LOGGING_LEVEL: DEBUG
    user: "${AIRFLOW_UID}:0"
    volumes:
      - ./workflow/dags:/opt/airflow/dags
      - ./workflow/logs:/opt/airflow/logs
      - ./workflow/plugins:/opt/airflow/plugins

    ports:
      - "8080:8080"
    networks:
      - default

  airflow-scheduler:
    image: apache/airflow:2.8.1
    command: scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@postgres:5432/airflow"
      AIRFLOW__CORE__FERNET_KEY: "${FERNET_KEY}"
    volumes:
      - ./workflow/dags:/opt/airflow/dags
      - ./workflow/logs:/opt/airflow/logs

    networks:
      - default
    restart: always
  
networks:
  default:
    external: true
    name: your-network # tên mạng đã được tạo trước đó
